// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SepetHesabıDataBase.Data;

#nullable disable

namespace SepetHesabıDataBase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SepetHesabıDataBase.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("urunAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("urunAdet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("urunFıyat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Uruns");
                });
#pragma warning restore 612, 618
        }
    }
}
